"""Add delivery address fields to Inquiry model

Revision ID: 089ef743e933
Revises: 
Create Date: 2026-03-02 15:36:26.554164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089ef743e933'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first with server_default
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_street', sa.String(length=200), nullable=True, server_default=''))
        batch_op.add_column(sa.Column('delivery_city', sa.String(length=100), nullable=True, server_default=''))
        batch_op.add_column(sa.Column('delivery_state', sa.String(length=100), nullable=True, server_default=''))
        batch_op.add_column(sa.Column('delivery_pincode', sa.String(length=20), nullable=True, server_default=''))
    
    # Update existing rows with default values
    op.execute("UPDATE inquiry SET delivery_street = 'N/A', delivery_city = 'N/A', delivery_state = 'N/A', delivery_pincode = '000000' WHERE delivery_street IS NULL")
    
    # Now make columns NOT NULL
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.alter_column('delivery_street', nullable=False)
        batch_op.alter_column('delivery_city', nullable=False)
        batch_op.alter_column('delivery_state', nullable=False)
        batch_op.alter_column('delivery_pincode', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.drop_column('delivery_pincode')
        batch_op.drop_column('delivery_state')
        batch_op.drop_column('delivery_city')
        batch_op.drop_column('delivery_street')

    # ### end Alembic commands ###
